### ISSUE TITLE
Add anchor links to headers

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc-website#49]
Anchor links next to headers can make it easier and more pleasant to link to certain sections in an HTML document. As an example, GitHub does this by showing a small link next to a heading when hovering.

This could be done with a Lua filter and a little bit of CSS. Untested PoC:

``` lua
function Header (h)
  if h.identifier ~= '' then
    h.content:insert(1, pandoc.Link({pandoc.Str '🔗'}, h.identifier), '', {class = 'anchor-link'})
    return h
  end
end
```

``` css
.anchor-link {
  position: relative;
  left: -1em;
  display: hidden;
}

h1:hover > .anchor-link, h2:hover > .anchor-link, h3:hover > .anchor-link {
  display: inline-block;
}
```
  
CC @cderv who came up with the idea.
